// ==============================================================================
// I-CAN PLATFORM — ACTION INGESTION & PERSISTENCE SERVICE
// Supports direct Supabase database & storage with offline local fallback
// ==============================================================================

import { supabase, isConfigured } from '@/services/supabase';
import { GreenAction, VerificationDecision } from '@/types';

const LOCAL_ACTIONS_KEY = 'i_can_submitted_actions';
const SEED_VERSION_KEY = 'i_can_seed_version_v2_2weeks';

// Generate dynamic ISO timestamp relative to now
const daysAgo = (days: number, hours: number = 0) => 
  new Date(Date.now() - days * 86400000 - hours * 3600000).toISOString();

export const SEEDED_INITIAL_ACTIONS: GreenAction[] = [
  // ==========================================================================
  // NADIA SAFIRA (School of Design - Top Student #1 BEKEN Leader)
  // ==========================================================================
  {
    id: 'act-nadia-01',
    userId: 'usr-student-003',
    userName: 'Nadia Safira & Tim',
    userFaculty: 'School of Design (SOD)',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    categoryId: 'tree',
    categoryName: 'Penanaman Bibit Pohon Keras (TFI)',
    categoryIcon: 'TreePine',
    submissionType: 'PENYULUHAN_AKSI_NYATA',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&auto=format&fit=crop&q=80',
    campaignUrl: 'https://www.instagram.com/reel/C_nadiaPohon2026',
    groupMembers: ['2602234567', '2602998811'],
    story: 'Penyuluhan pentingnya RTH kota di Instagram Reels (1.8k views) dan penanaman 5 bibit pohon tabebuya bersama pengelola taman kota Jakarta Barat. #TeachForIndonesia #FosteringandEmpowering #BinusianCommunityService 🌳',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_FULL',
    actionStep: 'FINAL_REPORT',
    surveyLocation: 'Taman Hutan Kota Jakarta Barat',
    partnerName: 'Bpk. Sutrisno (Pengelola Taman)',
    safetyAssessed: true,
    aiConfidence: 0.96,
    aiGuidelineScore: 0.94,
    aiCompletenessScore: 0.92,
    aiAnalysisReason: 'Terdeteksi 5 bibit pohon ditanam di tanah, jaket almamater BINUS dikenakan, caption IG memuat hashtag resmi TFI.',
    greenCoinsEarned: 25,
    carbonImpactKg: 5.0,
    satPointsEarned: 4,
    comservHoursEarned: 2.0,
    guidelineComplied: true,
    realActivityVerified: true,
    submittedAt: daysAgo(2, 3),
    verifiedAt: daysAgo(2, 1),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-nadia-02',
    userId: 'usr-student-003',
    userName: 'Nadia Safira & Tim',
    userFaculty: 'School of Design (SOD)',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    categoryId: 'biopori',
    categoryName: 'Pembuatan Lubang Biopori (TFI)',
    categoryIcon: 'Droplets',
    submissionType: 'PENYULUHAN_AKSI_NYATA',
    photoUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600&auto=format&fit=crop&q=80',
    campaignUrl: 'https://www.tiktok.com/@nadia.eco/video/bioporiPalmerah',
    groupMembers: ['2602234567', '2602998811'],
    story: 'Edukasi resapan air hujan di TikTok dan membuat 5 lubang biopori pipa PVC di area pemukiman warga RT 05 Palmerah.',
    gpsLat: -6.2025,
    gpsLng: 106.7811,
    status: 'APPROVED',
    decision: 'APPROVED_FULL',
    actionStep: 'FINAL_REPORT',
    surveyLocation: 'Area Resapan RT 05 / RW 03 Palmerah',
    partnerName: 'Ibu Ratna (Ketua RT 05)',
    safetyAssessed: true,
    aiConfidence: 0.94,
    aiGuidelineScore: 0.92,
    aiCompletenessScore: 0.90,
    aiAnalysisReason: 'Pengeboran biopori dan pemasangan pipa penutup terverifikasi fisik.',
    greenCoinsEarned: 20,
    carbonImpactKg: 0.5,
    satPointsEarned: 4,
    comservHoursEarned: 2.0,
    submittedAt: daysAgo(4, 5),
    verifiedAt: daysAgo(4, 2),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-nadia-03',
    userId: 'usr-student-003',
    userName: 'Nadia Safira',
    userFaculty: 'School of Design (SOD)',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    categoryId: 'vbl',
    categoryName: 'Video Based Learning (VBL)',
    categoryIcon: 'Video',
    submissionType: 'VIDEO_BASED_LEARNING',
    photoUrl: 'https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?w=600&auto=format&fit=crop&q=80',
    campaignUrl: 'https://youtube.com/watch?v=sampleVBL_TextileWaste',
    videoUrl: 'https://youtube.com/watch?v=sampleVBL_TextileWaste',
    actionStep: 'FINAL_REPORT',
    story: 'Membuat video edukasi 8 menit berjaket almamater BINUS "Desain Sirkular & Upcycling Limbah Tekstil". Sitasi format APA style terlampir lengkap di akhir video!',
    gpsLat: -6.2001,
    gpsLng: 106.7845,
    status: 'APPROVED',
    decision: 'APPROVED_FULL',
    aiConfidence: 0.95,
    aiGuidelineScore: 0.96,
    aiCompletenessScore: 0.92,
    aiAnalysisReason: 'Logo TFI di awal video terdeteksi, jaket almamater dikenakan, sitasi format APA Style ada di penutup.',
    greenCoinsEarned: 25,
    carbonImpactKg: 0.1,
    satPointsEarned: 3,
    comservHoursEarned: 1.5,
    guidelineComplied: true,
    realActivityVerified: true,
    submittedAt: daysAgo(6, 4),
    verifiedAt: daysAgo(6, 2),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-nadia-04',
    userId: 'usr-student-003',
    userName: 'Nadia Safira',
    userFaculty: 'School of Design (SOD)',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    categoryId: 'tumbler',
    categoryName: 'Pakai Tumbler & Zero Waste',
    categoryIcon: 'CupSoda',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1570554886111-e80fcca6a029?w=600&auto=format&fit=crop&q=80',
    story: 'Bawa tumbler stainless dan kotak makan guna ulang ke kantin lantai 2 BINUS Anggrek.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.97,
    aiGuidelineScore: 0.90,
    aiCompletenessScore: 0.94,
    aiAnalysisReason: 'Objek tumbler dan lokasi kampus terverifikasi akurat.',
    greenCoinsEarned: 10,
    carbonImpactKg: 0.05,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(1, 2),
    verifiedAt: daysAgo(1, 1),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-nadia-05',
    userId: 'usr-student-003',
    userName: 'Nadia Safira',
    userFaculty: 'School of Design (SOD)',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    categoryId: 'transport',
    categoryName: 'Shuttle Bus Kampus BINUS',
    categoryIcon: 'Bus',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=600&auto=format&fit=crop&q=80',
    story: 'Naik Shuttle Bus resmi BINUS dari Kampus Anggrek menuju Kampus Syahdan untuk kuliah Tipografi.',
    gpsLat: -6.2009,
    gpsLng: 106.7835,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.95,
    aiGuidelineScore: 0.90,
    aiCompletenessScore: 0.90,
    aiAnalysisReason: 'Terdeteksi armada shuttle bus BINUS di shelter resmi.',
    greenCoinsEarned: 15,
    carbonImpactKg: 0.12,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(3, 4),
    verifiedAt: daysAgo(3, 3),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-nadia-06',
    userId: 'usr-student-003',
    userName: 'Nadia Safira',
    userFaculty: 'School of Design (SOD)',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    categoryId: 'waste',
    categoryName: 'Pemilahan Daur Ulang Drop Point',
    categoryIcon: 'Trash2',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&auto=format&fit=crop&q=80',
    story: 'Memilah kertas sisa sketsa desain dan botol plastik di Drop Point Recycling SOD Lantai 4.',
    gpsLat: -6.2015,
    gpsLng: 106.7825,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.94,
    aiGuidelineScore: 0.88,
    aiCompletenessScore: 0.90,
    aiAnalysisReason: 'Pilah sampah teridentifikasi akurat pada bin pilah kampus.',
    greenCoinsEarned: 10,
    carbonImpactKg: 0.08,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(5, 6),
    verifiedAt: daysAgo(5, 4),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-nadia-07',
    userId: 'usr-student-003',
    userName: 'Nadia Safira',
    userFaculty: 'School of Design (SOD)',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    categoryId: 'tumbler',
    categoryName: 'Sosialisasi Zero Waste IG Reels',
    categoryIcon: 'Sparkles',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    story: 'Poster edukasi grafis digital "Stop Single-Use Plastic di Kampus" diunggah ke IG Stories & feed.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.92,
    aiGuidelineScore: 0.90,
    aiCompletenessScore: 0.88,
    greenCoinsEarned: 15,
    carbonImpactKg: 0.05,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(7, 2),
    verifiedAt: daysAgo(7, 1),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-nadia-08',
    userId: 'usr-student-003',
    userName: 'Nadia Safira',
    userFaculty: 'School of Design (SOD)',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    categoryId: 'tumbler',
    categoryName: 'Pakai Tumbler & Zero Waste Streak',
    categoryIcon: 'CupSoda',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    story: 'Refill air minum di dispenser Eco-Water Kampus Syahdan dengan botol kaca.',
    gpsLat: -6.2005,
    gpsLng: 106.784,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.96,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.05,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(8, 3),
    verifiedAt: daysAgo(8, 2),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-nadia-09',
    userId: 'usr-student-003',
    userName: 'Nadia Safira',
    userFaculty: 'School of Design (SOD)',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    categoryId: 'energy',
    categoryName: 'Hemat Energi Studio Desain',
    categoryIcon: 'Zap',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=600&auto=format&fit=crop&q=80',
    story: 'Mematikan 6 unit lampu dan proyektor studio setelah kelas asistensi selesai.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.91,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.04,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(9, 5),
    verifiedAt: daysAgo(9, 4),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-nadia-10',
    userId: 'usr-student-003',
    userName: 'Nadia Safira',
    userFaculty: 'School of Design (SOD)',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    categoryId: 'waste',
    categoryName: 'Drop Point Plastik Kantin Kijang',
    categoryIcon: 'Trash2',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1528323273322-d81458248d40?w=600&auto=format&fit=crop&q=80',
    story: 'Memasukkan 4 botol plastik minuman ke kotak daur ulang khusus mitra Bank Sampah.',
    gpsLat: -6.202,
    gpsLng: 106.783,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.93,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.06,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(11, 3),
    verifiedAt: daysAgo(11, 2),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-nadia-11',
    userId: 'usr-student-003',
    userName: 'Nadia Safira & Tim',
    userFaculty: 'School of Design (SOD)',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    categoryId: 'biopori',
    categoryName: 'Survei Lokasi Biopori Tahap 1 (TFI)',
    categoryIcon: 'Droplets',
    submissionType: 'PENYULUHAN_AKSI_NYATA',
    isSurveyProposal: true,
    actionStep: 'SURVEY_PROPOSAL',
    surveyLocation: 'Area Resapan RT 05 / RW 03 Palmerah',
    partnerName: 'Ibu Ratna (Ketua RT 05)',
    safetyAssessed: true,
    photoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&auto=format&fit=crop&q=80',
    story: 'Pengajuan survei pra-kegiatan pembuatan 5 lubang biopori. Koordinasi dengan warga setempat telah disetujui.',
    groupMembers: ['2602234567', '2602998811'],
    status: 'APPROVED',
    decision: 'APPROVED_FULL',
    aiConfidence: 0.95,
    greenCoinsEarned: 10,
    carbonImpactKg: 0,
    satPointsEarned: 0,
    comservHoursEarned: 0,
    submittedAt: daysAgo(12, 6),
    verifiedAt: daysAgo(12, 4),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-nadia-12',
    userId: 'usr-student-003',
    userName: 'Nadia Safira',
    userFaculty: 'School of Design (SOD)',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    categoryId: 'tumbler',
    categoryName: 'Pakai Tumbler Zero Waste Day 1',
    categoryIcon: 'CupSoda',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1570554886111-e80fcca6a029?w=600&auto=format&fit=crop&q=80',
    story: 'Awal komitmen hidup minim sampah dengan botol minum pribadi di kampus BINUS.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.95,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.05,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(14, 2),
    verifiedAt: daysAgo(14, 1),
    verifiedBy: 'Siska Amanda (SSO)',
  },

  // ==========================================================================
  // BUDI SANTOSO (School of Computer Science - Active Student #2 Top Contributor)
  // ==========================================================================
  {
    id: 'act-budi-01',
    userId: 'usr-student-001',
    userName: 'Budi Santoso & Tim',
    userFaculty: 'School of Computer Science (SOCS)',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    categoryId: 'tree',
    categoryName: 'Penanaman Bibit Pohon Keras (TFI)',
    categoryIcon: 'TreePine',
    submissionType: 'PENYULUHAN_AKSI_NYATA',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&auto=format&fit=crop&q=80',
    campaignUrl: 'https://www.instagram.com/reel/C_budiPohon123',
    groupMembers: ['2602199841', '2602188412'],
    story: 'Penyuluhan pentingnya penghijauan kota di IG Reels dan penanaman 5 bibit pohon buah produktif bersama pengelola taman setempat. #TeachForIndonesia #FosteringandEmpowering #BinusianCommunityService 🌳',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_FULL',
    actionStep: 'FINAL_REPORT',
    surveyLocation: 'Lahan Terbuka Hijau Kemanggisan',
    partnerName: 'Bpk. Ahmad (Pengurus RT 04)',
    safetyAssessed: true,
    aiConfidence: 0.94,
    aiGuidelineScore: 0.92,
    aiCompletenessScore: 0.90,
    aiAnalysisReason: 'Terdeteksi 5 bibit pohon ditanam di tanah, caption IG memuat hashtag resmi TFI & almamater tervalidasi.',
    greenCoinsEarned: 25,
    carbonImpactKg: 5.0,
    satPointsEarned: 4,
    comservHoursEarned: 2.0,
    guidelineComplied: true,
    realActivityVerified: true,
    submittedAt: daysAgo(0, 3),
    verifiedAt: daysAgo(0, 2),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-budi-02',
    userId: 'usr-student-001',
    userName: 'Budi Santoso & Tim',
    userFaculty: 'School of Computer Science',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    categoryId: 'biopori',
    categoryName: 'Survei Lokasi Biopori (TFI)',
    categoryIcon: 'Droplets',
    submissionType: 'PENYULUHAN_AKSI_NYATA',
    isSurveyProposal: true,
    actionStep: 'SURVEY_PROPOSAL',
    surveyLocation: 'Lahan Terbuka RT 04 / RW 02 Palmerah, Jakarta Barat',
    partnerName: 'Ibu Rahma (Ketua RT 04)',
    safetyAssessed: true,
    photoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&auto=format&fit=crop&q=80',
    story: 'Pengajuan survei pra-kegiatan: pengecekan kontur tanah dan pipa air bawah tanah sebelum pembuatan 5 lubang biopori. Koordinasi dengan warga setempat telah disetujui.',
    groupMembers: ['2602188412', '2602199841'],
    status: 'APPROVED',
    decision: 'APPROVED_FULL',
    aiConfidence: 0.95,
    aiGuidelineScore: 0.95,
    aiCompletenessScore: 0.92,
    aiAnalysisReason: 'Foto survei lokasi awal jelas, koordinasi pengelola RT terverifikasi dan pengecekan keamanan K3 valid.',
    greenCoinsEarned: 10,
    carbonImpactKg: 0,
    satPointsEarned: 0,
    comservHoursEarned: 0,
    submittedAt: daysAgo(1, 4),
    verifiedAt: daysAgo(1, 2),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-budi-03',
    userId: 'usr-student-001',
    userName: 'Budi Santoso',
    userFaculty: 'School of Computer Science',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    categoryId: 'transport',
    categoryName: 'Shuttle Bus Kampus BINUS',
    categoryIcon: 'Bus',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=600&auto=format&fit=crop&q=80',
    story: 'Naik Shuttle Bus BINUS Anggrek ke Kijang untuk mengurangi emisi kendaraan bermotor pribadi.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.95,
    greenCoinsEarned: 15,
    carbonImpactKg: 0.12,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(2, 5),
    verifiedAt: daysAgo(2, 4),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-budi-04',
    userId: 'usr-student-001',
    userName: 'Budi Santoso',
    userFaculty: 'School of Computer Science',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    categoryId: 'tumbler',
    categoryName: 'Pakai Tumbler Stainless Steel',
    categoryIcon: 'CupSoda',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1570554886111-e80fcca6a029?w=600&auto=format&fit=crop&q=80',
    story: 'Hari ke-5 bawa tumbler dan kotak makan guna ulang ke water station Lantai 1 BINUS Anggrek.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.96,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.05,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(3, 6),
    verifiedAt: daysAgo(3, 5),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-budi-05',
    userId: 'usr-student-001',
    userName: 'Budi Santoso',
    userFaculty: 'School of Computer Science',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    categoryId: 'waste',
    categoryName: 'Pemilahan Botol PET Drop Point SOCS',
    categoryIcon: 'Trash2',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&auto=format&fit=crop&q=80',
    story: 'Memilah 4 botol plastik kemasan di Drop Point Lantai 6 SOCS.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.94,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.08,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(5, 4),
    verifiedAt: daysAgo(5, 3),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-budi-06',
    userId: 'usr-student-001',
    userName: 'Budi Santoso',
    userFaculty: 'School of Computer Science',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    categoryId: 'energy',
    categoryName: 'Kampanye Hemat Energi Lab Komputer',
    categoryIcon: 'Zap',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80',
    story: 'Mematikan 12 unit monitor PC lab setelah sesi praktikum pemrograman web berakhir.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.92,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.04,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(6, 6),
    verifiedAt: daysAgo(6, 4),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-budi-07',
    userId: 'usr-student-001',
    userName: 'Budi Santoso',
    userFaculty: 'School of Computer Science',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    categoryId: 'tumbler',
    categoryName: 'Bawa Tumbler & Gelas Mandiri',
    categoryIcon: 'CupSoda',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    story: 'Refill air di galon laboratorium riset AI tanpa beli air kemasan sekali pakai.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.95,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.05,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(8, 2),
    verifiedAt: daysAgo(8, 1),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-budi-08',
    userId: 'usr-student-001',
    userName: 'Budi Santoso',
    userFaculty: 'School of Computer Science',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    categoryId: 'vbl',
    categoryName: 'Video Based Learning: Green Computing',
    categoryIcon: 'Video',
    submissionType: 'VIDEO_BASED_LEARNING',
    photoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80',
    campaignUrl: 'https://youtube.com/watch?v=sampleVBL_GreenCode',
    videoUrl: 'https://youtube.com/watch?v=sampleVBL_GreenCode',
    story: 'Video edukasi 7 menit "Algoritma Efisiensi Daya & Server Hijau" dengan sitasi format APA Style.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'PENDING',
    aiConfidence: 0.93,
    aiGuidelineScore: 0.92,
    aiCompletenessScore: 0.90,
    greenCoinsEarned: 25,
    carbonImpactKg: 0.1,
    satPointsEarned: 3,
    comservHoursEarned: 1.5,
    submittedAt: daysAgo(9, 4),
  },
  {
    id: 'act-budi-09',
    userId: 'usr-student-001',
    userName: 'Budi Santoso',
    userFaculty: 'School of Computer Science',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    categoryId: 'energy',
    categoryName: 'Jalan Tangga Manual Pengganti Lift',
    categoryIcon: 'Zap',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?w=600&auto=format&fit=crop&q=80',
    story: 'Gunakan tangga manual dari Lantai 1 ke Lantai 3 Gedung Anggrek untuk hemat listrik lift kampus.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.90,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.03,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(10, 3),
    verifiedAt: daysAgo(10, 2),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-budi-10',
    userId: 'usr-student-001',
    userName: 'Budi Santoso',
    userFaculty: 'School of Computer Science',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    categoryId: 'waste',
    categoryName: 'Drop Point E-Waste Mouse & Kabel Rusak',
    categoryIcon: 'Trash2',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1528323273322-d81458248d40?w=600&auto=format&fit=crop&q=80',
    story: 'Menaruh kabel charger bekas dan mouse rusak di kotak E-Waste drop point BINUS Syahdan.',
    gpsLat: -6.2005,
    gpsLng: 106.784,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.94,
    greenCoinsEarned: 15,
    carbonImpactKg: 0.20,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(12, 5),
    verifiedAt: daysAgo(12, 3),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-budi-11',
    userId: 'usr-student-001',
    userName: 'Budi Santoso',
    userFaculty: 'School of Computer Science',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    categoryId: 'transport',
    categoryName: 'Shuttle Bus Kampus Pagi',
    categoryIcon: 'Bus',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=600&auto=format&fit=crop&q=80',
    story: 'Naik bus kampus pukul 07.30 WIB untuk jadwal kuliah pagi.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.95,
    greenCoinsEarned: 15,
    carbonImpactKg: 0.12,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(13, 2),
    verifiedAt: daysAgo(13, 1),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-budi-12',
    userId: 'usr-student-001',
    userName: 'Budi Santoso',
    userFaculty: 'School of Computer Science',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    categoryId: 'tumbler',
    categoryName: 'Pakai Tumbler Zero Waste Day 1',
    categoryIcon: 'CupSoda',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1570554886111-e80fcca6a029?w=600&auto=format&fit=crop&q=80',
    story: 'Mulai program pengurangan sampah plastik sekali pakai di lingkungan kampus.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.95,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.05,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(14, 4),
    verifiedAt: daysAgo(14, 3),
    verifiedBy: 'Siska Amanda (SSO)',
  },

  // ==========================================================================
  // FARHAN RAMADHAN (Faculty of Engineering - Newbie Eco Student)
  // ==========================================================================
  {
    id: 'act-farhan-01',
    userId: 'usr-student-004',
    userName: 'Farhan Ramadhan',
    userFaculty: 'Faculty of Engineering',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    categoryId: 'vbl',
    categoryName: 'Video Based Learning (VBL)',
    categoryIcon: 'Video',
    submissionType: 'VIDEO_BASED_LEARNING',
    photoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80',
    campaignUrl: 'https://youtube.com/watch?v=sampleVBL_Ewaste',
    videoUrl: 'https://youtube.com/watch?v=sampleVBL_Ewaste',
    story: 'Video edukasi 6 menit "Cara Memilah & Mengelola Sampah Elektronik Rumah Tangga" dengan referensi APA Style.',
    gpsLat: -6.2012,
    gpsLng: 106.783,
    status: 'PENDING',
    aiConfidence: 0.90,
    aiGuidelineScore: 0.94,
    aiCompletenessScore: 0.88,
    aiAnalysisReason: 'Pengecekan visual mendeteksi jaket almamater dan durasi video memenuhi standar (6 min).',
    greenCoinsEarned: 25,
    carbonImpactKg: 0.1,
    satPointsEarned: 3,
    comservHoursEarned: 1.5,
    submittedAt: daysAgo(0, 1),
  },
  {
    id: 'act-farhan-02',
    userId: 'usr-student-004',
    userName: 'Farhan Ramadhan',
    userFaculty: 'Faculty of Engineering',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    categoryId: 'tumbler',
    categoryName: 'Bawa Tumbler ke Lab Mesin',
    categoryIcon: 'CupSoda',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1570554886111-e80fcca6a029?w=600&auto=format&fit=crop&q=80',
    story: 'Bawa tumbler kopi sendiri saat sesi praktikum bengkel mesin.',
    gpsLat: -6.2012,
    gpsLng: 106.783,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.95,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.05,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(2, 4),
    verifiedAt: daysAgo(2, 2),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-farhan-03',
    userId: 'usr-student-004',
    userName: 'Farhan Ramadhan',
    userFaculty: 'Faculty of Engineering',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    categoryId: 'transport',
    categoryName: 'Bike to Campus (Sepeda Lipat)',
    categoryIcon: 'Bus',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600&auto=format&fit=crop&q=80',
    story: 'Bersepeda dari kost Kemanggisan ke Kampus Anggrek untuk zero emission transit.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.94,
    greenCoinsEarned: 15,
    carbonImpactKg: 0.25,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(4, 3),
    verifiedAt: daysAgo(4, 1),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-farhan-04',
    userId: 'usr-student-004',
    userName: 'Farhan Ramadhan',
    userFaculty: 'Faculty of Engineering',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    categoryId: 'waste',
    categoryName: 'Pemilahan Logam dan Kabel Bekas',
    categoryIcon: 'Trash2',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&auto=format&fit=crop&q=80',
    story: 'Memilah sisa potongan kabel tembaga dan kaleng ke tempat daur ulang logam.',
    gpsLat: -6.2012,
    gpsLng: 106.783,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.92,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.15,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(6, 5),
    verifiedAt: daysAgo(6, 4),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-farhan-05',
    userId: 'usr-student-004',
    userName: 'Farhan Ramadhan',
    userFaculty: 'Faculty of Engineering',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    categoryId: 'energy',
    categoryName: 'Paperless Submission Tugas Praktikum',
    categoryIcon: 'Zap',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80',
    story: 'Mengumpulkan laporan praktikum secara 100% digital tanpa cetak kertas kalkir.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.89,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.02,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(7, 4),
    verifiedAt: daysAgo(7, 3),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-farhan-06',
    userId: 'usr-student-004',
    userName: 'Farhan Ramadhan',
    userFaculty: 'Faculty of Engineering',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    categoryId: 'tumbler',
    categoryName: 'Pakai Tumbler Harian',
    categoryIcon: 'CupSoda',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    story: 'Mengisi air minum di water station lantai 2 Engineering.',
    gpsLat: -6.2012,
    gpsLng: 106.783,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.95,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.05,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(9, 2),
    verifiedAt: daysAgo(9, 1),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-farhan-07',
    userId: 'usr-student-004',
    userName: 'Farhan Ramadhan',
    userFaculty: 'Faculty of Engineering',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    categoryId: 'transport',
    categoryName: 'Shuttle Bus Kampus Syahdan',
    categoryIcon: 'Bus',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=600&auto=format&fit=crop&q=80',
    story: 'Naik bus kampus sore hari ke halte Syahdan.',
    gpsLat: -6.2005,
    gpsLng: 106.784,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.94,
    greenCoinsEarned: 15,
    carbonImpactKg: 0.12,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(11, 4),
    verifiedAt: daysAgo(11, 3),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-farhan-08',
    userId: 'usr-student-004',
    userName: 'Farhan Ramadhan',
    userFaculty: 'Faculty of Engineering',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    categoryId: 'energy',
    categoryName: 'Aksi Bersih Ruang Lab & Matikan Lampu',
    categoryIcon: 'Zap',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=600&auto=format&fit=crop&q=80',
    story: 'Mematikan lampu dan AC ruang solder setelah selesai proyek mikrokontroler.',
    gpsLat: -6.2012,
    gpsLng: 106.783,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.90,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.04,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(13, 5),
    verifiedAt: daysAgo(13, 4),
    verifiedBy: 'Siska Amanda (SSO)',
  },

  // ==========================================================================
  // PEER STUDENTS (Kevin, Clarissa, Maya, Dimas, Rian)
  // ==========================================================================
  {
    id: 'act-peer-01',
    userId: 'usr-student-002',
    userName: 'Kevin Pratama',
    userFaculty: 'School of Information Systems',
    userAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    categoryId: 'waste',
    categoryName: 'Pemilahan Daur Ulang Drop Point',
    categoryIcon: 'Trash2',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&auto=format&fit=crop&q=80',
    story: 'Memilah 3 jenis botol plastik di Drop Point Recycling BINUS Syahdan.',
    gpsLat: -6.2005,
    gpsLng: 106.784,
    status: 'PENDING',
    aiConfidence: 0.95,
    aiGuidelineScore: 0.85,
    aiCompletenessScore: 0.90,
    aiAnalysisReason: 'Objek pemilahan sampah terdeteksi akurat di lokasi kampus.',
    greenCoinsEarned: 10,
    carbonImpactKg: 0.08,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(0, 2),
  },
  {
    id: 'act-peer-02',
    userId: 'usr-student-006',
    userName: 'Clarissa Putri',
    userFaculty: 'School of Design (SOD)',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    categoryId: 'vbl',
    categoryName: 'Video Based Learning (VBL)',
    categoryIcon: 'Video',
    submissionType: 'VIDEO_BASED_LEARNING',
    photoUrl: 'https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?w=600&auto=format&fit=crop&q=80',
    campaignUrl: 'https://youtube.com/watch?v=sampleVBL_Clarissa',
    videoUrl: 'https://youtube.com/watch?v=sampleVBL_Clarissa',
    actionStep: 'FINAL_REPORT',
    story: 'Edukasi 8 menit "Prinsip Upcycling Kemasan Bekas Mahasiswa". Sitasi format APA style terlampir lengkap!',
    gpsLat: -6.2001,
    gpsLng: 106.7845,
    status: 'APPROVED',
    decision: 'APPROVED_FULL',
    aiConfidence: 0.93,
    greenCoinsEarned: 25,
    carbonImpactKg: 0.1,
    satPointsEarned: 3,
    comservHoursEarned: 1.5,
    submittedAt: daysAgo(5, 3),
    verifiedAt: daysAgo(5, 1),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-peer-03',
    userId: 'usr-student-007',
    userName: 'Maya Anggraini',
    userFaculty: 'BINUS Business School (BBS)',
    userAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    categoryId: 'tumbler',
    categoryName: 'Bawa Totebag & Wadah Ramah Lingkungan',
    categoryIcon: 'CupSoda',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    story: 'Belanja buku dan alat tulis kampus menggunakan tas kain guna ulang.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.94,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.05,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(7, 3),
    verifiedAt: daysAgo(7, 2),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-peer-04',
    userId: 'usr-student-008',
    userName: 'Dimas Prakoso',
    userFaculty: 'School of Computer Science',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    categoryId: 'waste',
    categoryName: 'Aksi Bersih Drop Point Syahdan',
    categoryIcon: 'Trash2',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&auto=format&fit=crop&q=80',
    story: 'Membantu merapikan kardus kemasan bekas praktikum hardware komputer.',
    gpsLat: -6.2005,
    gpsLng: 106.784,
    status: 'APPROVED',
    decision: 'APPROVED_COINS_ONLY',
    aiConfidence: 0.91,
    greenCoinsEarned: 10,
    carbonImpactKg: 0.08,
    satPointsEarned: 0,
    comservHoursEarned: 0.0,
    submittedAt: daysAgo(10, 4),
    verifiedAt: daysAgo(10, 3),
    verifiedBy: 'Siska Amanda (SSO)',
  },
  {
    id: 'act-peer-05',
    userId: 'usr-student-009',
    userName: 'Rian Wijaya',
    userFaculty: 'BINUS Business School',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    categoryId: 'energy',
    categoryName: 'Kampanye Hemat Energi',
    categoryIcon: 'Zap',
    submissionType: 'SELF_GREEN_CAMPAIGN',
    photoUrl: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=600&auto=format&fit=crop&q=80',
    story: 'Mematikan lampu ruangan kelas setelah selesai kuliah.',
    gpsLat: -6.2017,
    gpsLng: 106.7822,
    status: 'REJECTED',
    decision: 'REJECTED',
    rejectionReason: 'Foto bukti terlalu gelap dan tidak memuat atribut identitas mahasiswa/kampus.',
    greenCoinsEarned: 0,
    carbonImpactKg: 0,
    satPointsEarned: 0,
    comservHoursEarned: 0,
    submittedAt: daysAgo(12, 4),
    verifiedAt: daysAgo(12, 2),
    verifiedBy: 'Siska Amanda (SSO)',
  },
];

// Retrieve all actions (from Supabase or LocalStorage fallback)
export async function getActions(): Promise<GreenAction[]> {
  if (isConfigured) {
    try {
      const { data, error } = await supabase
        .from('actions')
        .select(`
          *,
          users (full_name, nim),
          action_categories (name, icon, emission_factor, base_coins)
        `)
        .order('submitted_at', { ascending: false });

      if (!error && data) {
        return data.map((item: any) => ({
          id: item.id,
          userId: item.user_id,
          userName: item.users?.full_name || 'Mahasiswa BINUS',
          categoryId: item.category_id,
          categoryName: item.action_categories?.name || 'Aksi Hijau',
          categoryIcon: item.action_categories?.icon || 'Leaf',
          submissionType: item.submission_type,
          isSurveyProposal: item.is_survey_proposal,
          actionStep: item.action_step,
          surveyLocation: item.survey_location,
          partnerName: item.partner_name,
          safetyAssessed: item.safety_assessed,
          photoUrl: item.photo_url,
          campaignUrl: item.campaign_url,
          videoUrl: item.video_url,
          groupMembers: item.group_members,
          story: item.story,
          gpsLat: item.gps_lat,
          gpsLng: item.gps_lng,
          status: item.status,
          decision: item.decision,
          aiConfidence: item.ai_confidence,
          aiGuidelineScore: item.ai_guideline_score,
          aiCompletenessScore: item.ai_completeness_score,
          aiAnalysisReason: item.ai_analysis_reason,
          greenCoinsEarned: item.green_coins_earned,
          carbonImpactKg: item.carbon_impact_kg,
          satPointsEarned: item.sat_points_earned,
          comservHoursEarned: item.comserv_hours,
          guidelineComplied: item.guideline_complied,
          realActivityVerified: item.real_activity_verified,
          submittedAt: item.submitted_at,
          verifiedAt: item.verified_at,
          verifiedBy: item.verified_by,
          rejectionReason: item.rejection_reason,
        }));
      }
    } catch (err) {
      console.warn('Supabase fetch failed, falling back to local store:', err);
    }
  }

  // Check version to ensure latest 2-week rich records are populated
  const savedVersion = localStorage.getItem(SEED_VERSION_KEY);
  if (savedVersion !== 'v2.2') {
    localStorage.setItem(LOCAL_ACTIONS_KEY, JSON.stringify(SEEDED_INITIAL_ACTIONS));
    localStorage.setItem(SEED_VERSION_KEY, 'v2.2');
    return SEEDED_INITIAL_ACTIONS;
  }

  // Local fallback
  const raw = localStorage.getItem(LOCAL_ACTIONS_KEY);
  if (raw) {
    try {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed;
      }
    } catch {
      // fallback
    }
  }

  localStorage.setItem(LOCAL_ACTIONS_KEY, JSON.stringify(SEEDED_INITIAL_ACTIONS));
  return SEEDED_INITIAL_ACTIONS;
}

// Submit a new action
export async function submitGreenAction(
  actionData: Omit<GreenAction, 'id' | 'submittedAt'>,
  photoBlob?: Blob
): Promise<GreenAction> {
  let photoUrl = actionData.photoUrl;

  // 1. Upload photo to Supabase Storage if configured
  if (isConfigured && photoBlob) {
    try {
      const fileName = `${actionData.userId}/${Date.now()}.jpg`;
      const { error: uploadError } = await supabase.storage
        .from('action-photos')
        .upload(fileName, photoBlob, { contentType: 'image/jpeg' });

      if (!uploadError) {
        const { data: publicUrlData } = supabase.storage
          .from('action-photos')
          .getPublicUrl(fileName);
        photoUrl = publicUrlData.publicUrl;
      }
    } catch (err) {
      console.warn('Storage upload error, using local data URL:', err);
    }
  }

  const newAction: GreenAction = {
    ...actionData,
    id: `act-${Date.now()}`,
    photoUrl,
    submittedAt: new Date().toISOString(),
  };

  // 2. Insert record into Supabase table
  if (isConfigured) {
    try {
      const { data, error } = await supabase
        .from('actions')
        .insert({
          id: newAction.id,
          user_id: newAction.userId,
          category_id: newAction.categoryId,
          submission_type: newAction.submissionType,
          is_survey_proposal: newAction.isSurveyProposal,
          action_step: newAction.actionStep,
          survey_location: newAction.surveyLocation,
          partner_name: newAction.partnerName,
          safety_assessed: newAction.safetyAssessed,
          photo_url: newAction.photoUrl,
          campaign_url: newAction.campaignUrl,
          video_url: newAction.videoUrl,
          group_members: newAction.groupMembers,
          story: newAction.story,
          gps_lat: newAction.gpsLat,
          gps_lng: newAction.gpsLng,
          status: newAction.status,
          decision: newAction.decision,
          ai_confidence: newAction.aiConfidence,
          ai_guideline_score: newAction.aiGuidelineScore,
          ai_completeness_score: newAction.aiCompletenessScore,
          ai_analysis_reason: newAction.aiAnalysisReason,
          green_coins_earned: newAction.greenCoinsEarned,
          carbon_impact_kg: newAction.carbonImpactKg,
          sat_points_earned: newAction.satPointsEarned,
          comserv_hours: newAction.comservHoursEarned,
          guideline_complied: newAction.guidelineComplied,
          real_activity_verified: newAction.realActivityVerified,
          submitted_at: newAction.submittedAt,
        })
        .select()
        .single();

      if (!error && data) {
        return newAction;
      }
    } catch (err) {
      console.warn('Supabase insert failed, persisting locally:', err);
    }
  }

  // 3. Offline/Local persistence
  const actions = await getActions();
  const updated = [newAction, ...actions];
  localStorage.setItem(LOCAL_ACTIONS_KEY, JSON.stringify(updated));

  return newAction;
}

// Verifier Decision Update
export async function updateActionVerification(
  actionId: string,
  decision: VerificationDecision,
  verifierIdOrReason?: string,
  verifierName?: string,
  rejectionReason?: string
): Promise<GreenAction | null> {
  const isApproved = decision === 'APPROVED_FULL' || decision === 'APPROVED_COINS_ONLY';
  const status = isApproved ? 'APPROVED' : 'REJECTED';
  const now = new Date().toISOString();

  let finalVerifierId = 'usr-verifier-002';
  let finalVerifierName = 'Siska Amanda (SSO)';
  let finalReason = rejectionReason;

  if (verifierIdOrReason && verifierIdOrReason.startsWith('usr-')) {
    finalVerifierId = verifierIdOrReason;
    if (verifierName) finalVerifierName = verifierName;
  } else if (verifierIdOrReason) {
    finalReason = verifierIdOrReason;
  }

  if (verifierName && !verifierName.startsWith('usr-')) {
    finalVerifierName = verifierName;
  }

  if (isConfigured) {
    try {
      const { data, error } = await supabase
        .from('actions')
        .update({
          status,
          decision,
          verified_at: now,
          verified_by: finalVerifierName,
          rejection_reason: finalReason,
        })
        .eq('id', actionId)
        .select()
        .single();

      if (!error && data) {
        return {
          ...data,
          status,
          decision,
          verifiedAt: now,
          verifiedBy: finalVerifierName,
          rejectionReason: finalReason,
        };
      }
    } catch (err) {
      console.warn('Supabase update failed, updating locally:', err);
    }
  }

  // Local fallback update
  const actions = await getActions();
  const targetIndex = actions.findIndex((a) => a.id === actionId);
  if (targetIndex === -1) return null;

  const target = actions[targetIndex];
  const updatedAction: GreenAction = {
    ...target,
    status,
    decision,
    verifiedAt: now,
    verifiedBy: finalVerifierName,
    rejectionReason: finalReason || target.rejectionReason,
    // If coins only, sat points becomes 0
    satPointsEarned: decision === 'APPROVED_COINS_ONLY' ? 0 : target.satPointsEarned,
    comservHoursEarned: decision === 'APPROVED_COINS_ONLY' ? 0 : target.comservHoursEarned,
    realActivityVerified: decision === 'APPROVED_FULL',
  };

  actions[targetIndex] = updatedAction;
  localStorage.setItem(LOCAL_ACTIONS_KEY, JSON.stringify(actions));

  return updatedAction;
}

// Get user specific actions
export async function getUserActions(userId: string): Promise<GreenAction[]> {
  const all = await getActions();
  return all.filter((a) => a.userId === userId);
}
